### PR TITLE
Improve recognize link algorithm

### PR DESCRIPTION
**Pull request by bogem**
* Improve performance
* Easier to read

### CODE REVIEW

**Comment by gazay** [comment]
I see how it can be easier to read but don't see performance improvement. Same count of iterations througn IdsPlease::Parsers::NETWORKS.values as before, same count of matchings

**Comment by bogem** [comment]
Hm. Yes, about performance I ain't correct 
But it obviously better than old algorithm 😊

**Comment by gazay** [comment]
For me, it's pretty the same but I'm ok merge this because it's slightly more readable, you right.

**Comment by bogem** [comment]
Thanks!

**Comment by gazay** [comment]
No, thank you =)

**Comment by bogem** [comment]
☺️

**Pull request merged**
