### PR TITLE
Executable

### PR DESCRIPTION
**Pull request by bogem**
Close https://github.com/gazay/ids_please/issues/11
Add executable to project
It works with `grab`, `parse` and `recognize` methods
See `ids_please help` for instructions

TODO: need to document it in README (Also I can try to document it)

### CODE REVIEW

**Comment by gazay** [comment]
A lot of code in binary is not a good sign. Maybe better to create a new class like IdsPlease::CLI or Console or Cmd (or whatever) and put all logic there? And from binary only require it and run something like `IdsPlease::Cli.new(ARGV).run`. It allows to test that logic in isolation easy way.

And I don't like solution with using many `puts` instead of multiline string syntax.

Also, there is possibility that gem can be used from source, without loading its classes in LOAD_PATH. In that case just `require 'ids_please'` will throw an error. You can look how I've solved it here: https://github.com/gazay/talks/blob/master/bin/talking

And the best thing for CLI tool creation with options parsing, automatic help message generation, etc. is thor (https://github.com/erikhuda/thor)

**Comment by bogem** [comment]
Ok. Will do it
I thought about Thor, but also I thought, that you don't like this idea, because ids_please hasn't got any dependencies and obviously not all people will use CLI version. So add a single dependency for only CLI version - bad idea

**Comment by bogem** [comment]
And why you don't like using many puts instead of multiline string syntax?

**Comment by gazay** [comment]
I agree that thor is not needed here as not so many logic and options in CLI.

Many puts with many strings 1) looks not clean 2) many excess objects (strings) 3) many excess IO operations instead of one

**Comment by bogem** [comment]
Ok. I haven't thought about it.
Btw I almost done

**Comment by bogem** [comment]
Updated. What about now?

**Comment by bogem** [comment]
You're right about multi-line strings: they're prettier than a lot of puts

**Comment by gazay** [comment]
Thank you! Yes, that's better. I'll refactor it a little later as there are some logic that not related to CLI but to grabbers and parsers itself.

**Comment by bogem** [comment]
And we should said about CLI version in README

**Pull request merged**
